PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl:  <http://www.w3.org/2002/07/owl#>
prefix obo:  <http://purl.obolibrary.org/obo/>

construct {
#        ?assay rdfs:subClassOf  [ owl:intersectionOf [  rdf:first  [ a owl:Restriction ;
#                                                                     owl:onProperty <http://purl.obolibrary.org/obo/BFO_0000055> ;
#                                                                     owl:someValuesFrom [ owl:intersectionOf  [ rdf:first  <http://purl.obolibrary.org/obo/OBI_0000275> ]] ] ;
#                                                                                                                rdf:rest  [ rdf:first [ a owl:Restriction ;
#                                                                                                                                        owl:onProperty <http://purl.obolibrary.org/obo/RO_0000081> ;
#                                                                                                                                        owl:someValuesFrom  [ owl:intersectionOf  [ rdf:first ?targent ] ] ] ]  ]  ] .
#        ?assay rdfs:subClassOf  [ owl:intersectionOf [  rdf:first  [ a owl:Restriction ;
#                                                                     owl:onProperty <http://purl.obolibrary.org/obo/OBI_0000293> ;
#                                                                     owl:someValuesFrom [ owl:intersectionOf  [ rdf:first  ?targent ]] ] ;
#                                                                                                                rdf:rest  [ rdf:first [ a owl:Restriction ;
#                                                                                                                                        owl:onProperty <http://purl.obolibrary.org/obo/RO_0000087> ;
#                                                                                                                                        owl:someValuesFrom  [ owl:intersectionOf  [ rdf:first <http://purl.obolibrary.org/obo/OBI_0000275> ] ] ] ]  ]  ] .

        ?assay rdfs:subClassOf [ owl:intersectionOf ( [ rdf:type owl:Restriction ;
                                                         owl:onProperty obo:BFO_0000055 ;
                                                         owl:someValuesFrom [ owl:intersectionOf ( obo:OBI_0000275
                                                                                                   [ rdf:type owl:Restriction ;
                                                                                                     owl:onProperty obo:RO_0000052 ;
                                                                                                     owl:someValuesFrom obo:CHEBI_17234
                                                                                                   ]
                                                                                                 ) ;
                                                                              rdf:type owl:Class
                                                                            ]
                                                       ]
                                                       [ rdf:type owl:Restriction ;
                                                         owl:onProperty obo:OBI_0000293 ;
                                                         owl:someValuesFrom ?targent
                                                       ]
                                                     ) ;
                                  rdf:type owl:Class
                                ] .

} where {
    ?assay rdfs:subClassOf  [ a owl:Restriction ;
                              owl:onProperty <http://purl.obolibrary.org/obo/OBI_0000299> ;
                              owl:someValuesFrom [ a owl:Restriction ;
                                                   owl:onProperty <http://purl.obolibrary.org/obo/IAO_0000136> ;
                                                   owl:someValuesFrom ?targent ;
                                                   ]  ] .
    values ?eligible {
        <http://purl.obolibrary.org/obo/CHEBI_23367> <http://purl.obolibrary.org/obo/CHEBI_33250>
    }
#    ?targent rdfs:subClassOf* <http://purl.obolibrary.org/obo/CHEBI_23367> .
    ?targent rdfs:subClassOf* ?eligible .

}