PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
select ?specific_sfo (lcase(str(?l)) as ?label)  (count(distinct ?parent ) as ?parent_count)  (count(distinct ?OEC ) as ?equivalent_count) where {
    ?specific_sfo rdfs:subClassOf* <http://purl.obolibrary.org/obo/OBI_0001479> ;
                                 rdfs:label ?l .
    optional {
        ?specific_sfo rdfs:subClassOf* ?parent .
        filter(isblank( ?parent ))
    }
    optional {
        ?specific_sfo owl:equivalentClass  ?OEC .
        filter(isblank( ?OEC ))
    }
}
group by ?specific_sfo ?l
