PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select
?sfo ?sfolab ?tissue ?tisslab
where {
    ?sfo <http://www.w3.org/2002/07/owl#equivalentClass> ?x5 ;
         rdfs:label ?sfolab .
    ?x5 <http://www.w3.org/2002/07/owl#intersectionOf> ?x4  .
    ?x4 rdf:first ?x3  .
    ?x3 <http://www.w3.org/2002/07/owl#intersectionOf> ?x2 .
    ?x2 rdf:first <http://purl.obolibrary.org/obo/OBI_0100051> ;
        rdf:rest ?x1  .
    ?x1 rdf:first ?x1f ;
        rdf:rest ?x1r .
    ?x1f  a owl:Restriction ;
          owl:onProperty <http://purl.obolibrary.org/obo/OBI_0000312> ;
          owl:someValuesFrom <http://purl.obolibrary.org/obo/OBI_0600005> .
    ?x1r rdf:first ?x1rf .
    ?x1rf a  owl:Restriction ;
          owl:onProperty <http://purl.obolibrary.org/obo/RO_0001000> ;
          owl:someValuesFrom ?tissue .
    ?tissue rdfs:label ?tisslab .
}
